[build]
  publish = "."
  functions = "netlify/functions"
  command = "node generate-token-config.cjs"
  environment = { SECRETS_SCAN_OMIT_PATHS = "token-config.js" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
